name: flutter_base_project
description: Scaffold project with all basic setup.

version: 1.0.0+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

  easy_localization: ^2.0.2

  device_info: ^0.4.2+1

  package_info: ^0.4.0+16

  sentry: ^3.0.1

  url_launcher: ^5.4.2

  #Firebase
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.11
  firebase_performance: ^0.3.1+8
  firebase_remote_config: ^0.3.0+3

  performance_interceptor:
    git:
      url: https://github.com/solutelabs/firebase_performance_interceptor.git

  connectivity: ^0.4.8+2
  shared_preferences: ^0.5.6+3
  permission_handler: ^5.0.0+hotfix.1
  cached_network_image: ^2.0.0
  path_provider: ^1.6.5
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1


flutter:
  uses-material-design: true

  assets:
    # Localized strings
    - lib/assets/strings/
