name: flutter_base_project
description: Scaffold project with all basic setup.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  easy_localization: ^1.3.1

  device_info: ^0.4.1+4

  package_info: ^0.4.0+13

  sentry: ^3.0.0+1

  #Firebase
  firebase_crashlytics: ^0.1.2+4
  firebase_analytics: ^5.0.9
  firebase_performance: ^0.3.1+5

  performance_interceptor:
    git:
      url: git@gitlab.com:milind.mevada/firebase_performance_interceptor.git

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    # Localized strings
    - lib/assets/strings/
